resolver: lts-6.6
allow-newer: true
packages:
- '.'
- '../lnforum-ui-core'
- '../lnforum-sanitize'
- '../lnforum-validate'
- '../lnforum-api'
- '../lnforum-types-gen'
- '../haskell-api-helpers-shared'
- '../haskell-api-helpers'
- '../haskell-bbcode-parser'
- '../haskell-bbcode-parser-reactflux'
- '../haskell-media-embed'
- '../haskell-media-embed-reactflux'
- '../haskell-either-helpers'
- '../haskell-ebyam'
- '../haskell-ifte'
- '../haskell-rehtie'
- '../haskell-web-bootstrap'
- '../react-flux-router'
- '../ghcjs-router'
- '../ghcjs-ajax/ghcjs-ajax'
- '../web-routes' ## <-- custom web-routes with my fromPathInfoParams function
extra-deps:
- haskell-src-exts-1.16.0.1
- react-flux-1.1.1
- ref-tf-0.4
- html-entities-1.1.2
- http-client-0.5.14
- http-client-tls-0.3.4
- http-conduit-2.2.3.1
- wreq-0.5.0.1
flags: {}
extra-package-dbs: []
