resolver: lts-6.30

compiler: ghcjs-0.2.0.9006030_ghc-7.10.3
compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.9006030_ghc-7.10.3:
         url: http://ghcjs.tolysz.org/lts-6.30-9006030.tar.gz
         sha1: 2371e2ffe9e8781808b7a04313e6a0065b64ee51

allow-newer: true
packages:
- '.'
- '../lnforum-ui-core'
- '../lnforum-sanitize'
- '../lnforum-validate'
- '../lnforum-api-ghcjs'
- '../lnforum-types-gen'
- '../haskell-api-helpers-shared'
- '../haskell-api-helpers-ghcjs'
- '../haskell-bbcode-parser'
- '../haskell-bbcode-parser-reactflux'
- '../haskell-media-embed'
- '../haskell-media-embed-reactflux'
- '../haskell-either-helpers'
- '../haskell-ebyam'
- '../haskell-ifte'
- '../haskell-rehtie'
- '../haskell-web-bootstrap'
- '../react-flux-router'
- '../ghcjs-router'
- '../ghcjs-ajax/ghcjs-ajax'
extra-deps:
- haskell-src-exts-1.16.0.1
- react-flux-1.1.1
- ref-tf-0.4
- html-entities-1.1.2
- http-client-0.5.14
- http-client-tls-0.3.4
- http-conduit-2.2.3.1
- wreq-0.5.0.1
- web-routes-0.27.14.2
flags: {}
extra-package-dbs: []
